name: listo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  flutter_riverpod: ^0.14.0+3
  hooks_riverpod: ^0.14.0+5
  flutter_hooks: ^0.18.0
  bloc: ^7.2.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.7
  injector: ^2.0.0
  reactive_forms: ^10.6.0
  font_awesome_flutter: ^9.1.0
  page_view_indicators: ^2.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  carousel_slider: ^4.0.0
  flutter_carousel_slider: ^1.0.8
  sliding_up_panel: ^2.0.0+1
  fl_chart: ^0.36.2
  percent_indicator: ^3.0.1
  http: ^0.13.3
  flutter_secure_storage: ^4.2.1
  reactive_dropdown_search: ^0.2.1
  sizer: ^2.0.15
  responsive_framework: ^0.1.4
  string_validator: ^0.3.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  flutter_launcher_icons: ^0.9.2
  rename: ^1.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/listo.png"
  adaptive_icon_background: "assets/icon/listo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Generar código de internacionalización flutter gen en .dart_tool
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/font/Roboto-Bold.ttf

    - family: Roboto-Light
      fonts:
        - asset: assets/font/Roboto-Light.ttf

    - family: Roboto-Medium
      fonts:
        - asset: assets/font/Roboto-Medium.ttf

    - family: Roboto-Regular
      fonts:
        - asset: assets/font/Roboto-Regular.ttf

  assets:
    - assets/img/
    - assets/icon/
    - assets/font/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: es_CO
  enabled: true
